apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.objectengine.name }}
  labels:
    app: {{ .Values.images.objectengine.name }}
    chart: {{ .Values.images.objectengine.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.images.objectengine.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.images.objectengine.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.images.objectengine.name }}
          image: "{{ .Values.images.openscout.repository }}:{{ .Values.images.openscout.tag }}"
          imagePullPolicy: {{ .Values.images.openscout.pullPolicy }}
          command: {{ .Values.images.objectengine.command }}
          args: {{ .Values.images.objectengine.args }}   
          env:
            - name: "WEBSERVER"
              value: "{{.Values.images.httpd.url}}:{{.Values.images.httpd.nodePort}}"
          volumeMounts:
          - name: modeldir
            mountPath: "/openscout-server/models"
          - name: cachedir
            mountPath: "/root/.cache/torch/hub"
      #These containers are run during pod initialization
      initContainers:
        {{ if .Values.model.url }}
        - name: prepare-model
          image: busybox:1.28
          command:
            - wget
            - "-O"
            - {{ printf "%s/%s" "/openscout-server/models" .Values.model.name }}
            - {{.Values.model.url}}
          volumeMounts:
            - name: modeldir
              mountPath: "/openscout-server/models"
        {{ end }}
        - name: prepare-model-2
          image: busybox:1.28
          command:
            - wget
            - "-O"
            - "/root/.cache/torch/hub/master.zip"
            - "http://vm039.elijah.cs.cmu.edu:81/master.zip"
          volumeMounts:
            - name: cachedir
              mountPath: "/root/.cache/torch/hub"
      volumes:
        - name: modeldir
          emptyDir: {}
        - name: cachedir
          emptyDir: {}


